# Generated by Django 5.1.4 on 2025-01-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_usersettings_created_at_usersettings_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='allowed_ip',
            field=models.JSONField(blank=True),
        ),
    ]
